[package]
name = "s2-dbpf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binrw = "0.8"
const_format = { version = "0.2", features = ["fmt", "const_generics"] }