////////////////////////////////////////////////////////////////////////////////
// This Source Code Form is subject to the terms of the Mozilla Public         /
// License, v. 2.0. If a copy of the MPL was not distributed with this         /
// file, You can obtain one at https://mozilla.org/MPL/2.0/.                   /
////////////////////////////////////////////////////////////////////////////////

mod animation;
pub mod audio_file;
pub mod audio_reference;
pub mod behavior_constant;
pub mod behavior_constant_labels;
pub mod behavior_flowchart_tree;
pub mod behavior_function;
pub mod behavior_function_labels;
pub mod binary_index;
pub mod bitmap_image;
pub mod catalog_description;
pub mod catalog_string;
pub mod cinematic_scene;
mod content_registry;
mod creation_resource;
pub mod database_packed_file;
pub mod directory;
mod draw_state_lighting;
pub mod drawgroup;
mod effects_resource_tree;
pub mod environment_cube_lighting;
pub mod fence_post_layer;
pub mod function;
mod geometric_data_container;
pub mod geometric_node;
pub mod global_data;
pub mod hitlist;
pub mod house_descriptor;
mod id_number;
pub mod image_color_palette;
pub mod image_link;
pub mod jpeg_image;
mod large_image;
mod light;
pub mod lightmap;
mod linear_fog_lighting;
mod lot;
pub mod lot_definition;
mod lot_terrain_geometry;
pub mod lot_texture;
pub mod material_object;
mod maxis_material_shader;
pub mod name_map;
pub mod name_reference;
mod neighborhood;
pub mod object;
pub mod object_data;
pub mod object_function;
pub mod object_metadata;
pub mod object_slot;
pub mod package_toolkit;
pub mod pie_menu_functions;
pub mod pie_menu_settings;
pub mod pool_surface;
pub mod predictive_maps;
mod property_set;
pub mod roof;
pub mod scene_node;
mod shape;
mod sim;
mod singular_lot_object;
pub mod skintone_xml;
pub mod sound_effects;
pub mod sprites;
pub mod stack_script;
mod string_map;
pub mod text_lists;
pub mod texture_overlay_xml;
pub mod texture_resource;
pub mod textured_material;
pub mod three_d_array;
mod three_d_reference;
pub mod track_settings;
mod tssg_system;
pub mod two_d_array;
pub mod ui_data;
pub mod unknown1;
pub mod unknown2;
mod unknown3;
mod unknown4;
pub mod unknown_object;
mod version_information;
mod vertex_layer;
pub mod wall_graph;
pub mod wall_layer;
pub mod world_database;
