////////////////////////////////////////////////////////////////////////////////
// This Source Code Form is subject to the terms of the Mozilla Public         /
// License, v. 2.0. If a copy of the MPL was not distributed with this         /
// file, You can obtain one at https://mozilla.org/MPL/2.0/.                   /
////////////////////////////////////////////////////////////////////////////////

use binrw::{binrw, NullString};

#[binrw]
#[derive(PartialEq, Debug)]
struct ObjectData {
    #[brw(pad_size_to = 64)]
    filename: NullString,
    version: u32,
    initial_stack_size: u16,
    default_wall_adjacent_flags: u16,
    default_placement_flags: u16,
    default_wall_placement_flags: u16,
    default_allowed_height_flags: u16,
    interaction_table_id: u16,
    interaction_group: u16,
    type_of_object: u16,
    multi_tile_master_id: u16,
    multi_tile_sub_index: u16,
    use_default_placement_flags: u16,
    look_at_score: u16,
    guid: u32,
    item_is_unlockable: u16,
    catalog_use_flags: u16,
    price: u16,
    body_strings_id: u16,
    slot_id: u16,
    diagonal_selector_guid: u32,
    grid_aligned_selector_guid: u32,
    object_ownership_flags: u16,
    ignore_globalsim_in_cas_lot: u16,
    cannot_move_out_with: u16,
    hauntable: u16,
    proxy_guid: u32,
    slot_group: u16,
    aspiration_flags: u16,
    memory_nice_or_bad: u16,
    sale_price_different: u16,
    initial_depreciation: u16,
    daily_depreciation: u16,
    self_depreciation: u16,
    deprecation_limit: u16,
    room_sort_flags: u16,
    function_sort_flags: u16,
    catalog_strings_id: u16,
    is_global_sim_object: u16,
    tooltip_name_type: u16,
    template_version: u16,
    niceness_multiplier: u16,
    no_duplicate_on_placement: u16,
    want_category: u16,
    no_new_name_from_template: u16,
    object_version: u16,
    default_thumbnail_id: u16,
    motive_effects_id: u16,
    job_object_guid: u32,
    catalog_popup_id: u16,
    ignore_current_model_index_in_icons: u16,
    level_offset: u16,
    shadow_type: u16,
    num_attributes: u16,
    num_object_arrays: u16,
    unused: u16,
    front_direction: u16,
    unused_1: u16,
    multitile_lead_object: u16,
    expansion_flags: u16,
    unused_2: u16,
    chair_entry_flags: u16,
    tile_width: u16,
    inhibit_suit_copying: u16,
    build_mode_type: u16,
    original_guid: u32,
    object_model_guid: u32,
    build_mode_subsort: u16,
    unused_3: u16,
    unused_4: u16,
    footprint_mask: u16,
    unused_5: u16,
    unused_6: u16,
    unused_7: u16,
    unused_8: u16,
    hunger_rating: u16,
    comfort_rating: u16,
    hygiene_rating: u16,
    bladder_rating: u16,
    energy_rating: u16,
    fun_rating: u16,
    room_rating: u16,
    skill_flags: u16,
    num_type_attributes: u16,
    misc_flags: u16,
    unused_9: u16,
    function_subsort: u16,
    downtown_sort: u16,
    keep_buying: u16,
    vacation_sort: u16,
    reset_lot_action: u16,
    three_d_object_type: u16,
    community_sort_flags: u16,
    dream_flags: u16,
    /*
    #[deku(pad_bytes_before = "12")]
    filename_closer: String,
     */
}
