////////////////////////////////////////////////////////////////////////////////
// This Source Code Form is subject to the terms of the Mozilla Public         /
// License, v. 2.0. If a copy of the MPL was not distributed with this         /
// file, You can obtain one at https://mozilla.org/MPL/2.0/.                   /
////////////////////////////////////////////////////////////////////////////////

use binrw::{binrw, NullString};

#[binrw]
#[derive(PartialEq, Debug)]
pub struct ObjectData {
    #[brw(pad_size_to = 64)]
    pub filename: NullString,
    pub version: u32,
    pub initial_stack_size: u16,
    pub default_wall_adjacent_flags: u16,
    pub default_placement_flags: u16,
    pub default_wall_placement_flags: u16,
    pub default_allowed_height_flags: u16,
    pub interaction_table_id: u16,
    pub interaction_group: u16,
    pub type_of_object: u16,
    pub multi_tile_master_id: u16,
    pub multi_tile_sub_index: u16,
    pub use_default_placement_flags: u16,
    pub look_at_score: u16,
    pub guid: u32,
    pub item_is_unlockable: u16,
    pub catalog_use_flags: u16,
    pub price: u16,
    pub body_strings_id: u16,
    pub slot_id: u16,
    pub diagonal_selector_guid: u32,
    pub grid_aligned_selector_guid: u32,
    pub object_ownership_flags: u16,
    pub ignore_globalsim_in_cas_lot: u16,
    pub cannot_move_out_with: u16,
    pub hauntable: u16,
    pub proxy_guid: u32,
    pub slot_group: u16,
    pub aspiration_flags: u16,
    pub memory_nice_or_bad: u16,
    pub sale_price_different: u16,
    pub initial_depreciation: u16,
    pub daily_depreciation: u16,
    pub self_depreciation: u16,
    pub deprecation_limit: u16,
    pub room_sort_flags: u16,
    pub function_sort_flags: u16,
    pub catalog_strings_id: u16,
    pub is_global_sim_object: u16,
    pub tooltip_name_type: u16,
    pub template_version: u16,
    pub niceness_multiplier: u16,
    pub no_duplicate_on_placement: u16,
    pub want_category: u16,
    pub no_new_name_from_template: u16,
    pub object_version: u16,
    pub default_thumbnail_id: u16,
    pub motive_effects_id: u16,
    pub job_object_guid: u32,
    pub catalog_popup_id: u16,
    pub ignore_current_model_index_in_icons: u16,
    pub level_offset: u16,
    pub shadow_type: u16,
    pub num_attributes: u16,
    pub num_object_arrays: u16,
    pub unused: u16,
    pub front_direction: u16,
    pub unused_1: u16,
    pub multitile_lead_object: u16,
    pub expansion_flags: u16,
    pub unused_2: u16,
    pub chair_entry_flags: u16,
    pub tile_width: u16,
    pub inhibit_suit_copying: u16,
    pub build_mode_type: u16,
    pub original_guid: u32,
    pub object_model_guid: u32,
    pub build_mode_subsort: u16,
    pub unused_3: u16,
    pub unused_4: u16,
    pub footprint_mask: u16,
    pub unused_5: u16,
    pub unused_6: u16,
    pub unused_7: u16,
    pub unused_8: u16,
    pub hunger_rating: u16,
    pub comfort_rating: u16,
    pub hygiene_rating: u16,
    pub bladder_rating: u16,
    pub energy_rating: u16,
    pub fun_rating: u16,
    pub room_rating: u16,
    pub skill_flags: u16,
    pub num_type_attributes: u16,
    pub misc_flags: u16,
    pub unused_9: u16,
    pub function_subsort: u16,
    pub downtown_sort: u16,
    pub keep_buying: u16,
    pub vacation_sort: u16,
    pub reset_lot_action: u16,
    pub three_d_object_type: u16,
    pub community_sort_flags: u16,
    pub dream_flags: u16,
    /*
    #[deku(pad_bytes_before = "12")]
    filename_closer: String,
     */
}
