[package]
name = "s2-dbpf-raw-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
quote-use = "0.5"
proc-macro2 = "1.0"
proc-macro-error = "1.0"

[dev-dependencies]
binrw = "0.9"
